/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:db60cbc3-bbd4-4c16-8b22-5b3bc14a30d7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FXsrYR7p7",
    "aws_user_pools_web_client_id": "12ltf9ifdaj3pk6bj60j6qbgdb",
    "oauth": {}
};


export default awsmobile;
